### PR TITLE
use the modern constructor

### PR DESCRIPTION
**Pull request by aoloe**
this should work (better or only) on any somehow runnable php...

### CODE REVIEW

**Comment by gauthierm** [comment]
This bumps the required PHP version from 4.3 to 5.0. The package2.xml and composer.json should be updated.

Presumably this is done for PHP 7 support, it may make sense to update the method signatures and class properties to use PHP 5 syntax as well.

**Comment by aoloe** [comment]
in my case i already have problems with php 5.6...

and since i don't think that anybody still using php4 will be updating any code (or at least: i hope that nobody is doing so!) i hope that the patch will get accepted...

**Comment by golgote** [comment]
ok for me

**Comment by ftzdomino** [comment]
If the package2.xml and composer.json are updated, will this get accepted?

**Comment by cweiske** [comment]
- HTML_Common still uses the PHP4-style constructor, so I don't see why PHP 5.6 should bring any errors
- package2.xml and composer.json updates need to be done separate from this PR.

**Comment by cweiske** [comment]
Solved in PR#3.

**Pull request closed without merging**
